<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Challenge-2" data-toc-modified-id="Challenge-2-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Challenge 2</a></span><ul class="toc-item"><li><span><a href="#Problem-Solving-Iteration-1" data-toc-modified-id="Problem-Solving-Iteration-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Problem Solving Iteration 1</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed." data-toc-modified-id="The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed.-1.1.0.1"><span class="toc-item-num">1.1.0.1&nbsp;&nbsp;</span>The <code>Total</code> field is computed based on <code>HP</code>, <code>Attack</code>, <code>Defense</code>, <code>Sp. Atk</code>, <code>Sp. Def</code>, and <code>Speed</code>.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-2" data-toc-modified-id="Problem-Solving-Iteration-2-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Problem Solving Iteration 2</a></span><ul class="toc-item"><li><span><a href="#Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?" data-toc-modified-id="Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Which pokemon type is most likely to have the highest <code>Total</code> value?</a></span><ul class="toc-item"><li><span><a href="#Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type." data-toc-modified-id="Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type.-1.2.1.1"><span class="toc-item-num">1.2.1.1&nbsp;&nbsp;</span><code>Type 1</code> and <code>Type 2</code> string variables need to be converted to numerical variables in order to identify the relationship between <code>Total</code> and the pokemon type.</a></span></li><li><span><a href="#How-to-convert-two-string-variables-to-numerical?" data-toc-modified-id="How-to-convert-two-string-variables-to-numerical?-1.2.1.2"><span class="toc-item-num">1.2.1.2&nbsp;&nbsp;</span>How to convert two string variables to numerical?</a></span></li><li><span><a href="#In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create." data-toc-modified-id="In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create.-1.2.1.3"><span class="toc-item-num">1.2.1.3&nbsp;&nbsp;</span>In the next cell, use One Hot Encoding to encode <code>Type 1</code> and <code>Type 2</code>. Use the pokemon type values as the names of the numerical fields you create.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-3" data-toc-modified-id="Problem-Solving-Iteration-3-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Problem Solving Iteration 3</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations." data-toc-modified-id="There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations.-1.3.0.1"><span class="toc-item-num">1.3.0.1&nbsp;&nbsp;</span>There are relationships between <code>Total</code> and the encoded pokemon type variables and we need to identify the correlations.</a></span></li><li><span><a href="#How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?" data-toc-modified-id="How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?-1.3.0.2"><span class="toc-item-num">1.3.0.2&nbsp;&nbsp;</span>How to identify the relationship between <code>Total</code> and the encoded pokemon type fields?</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Bonus-Question" data-toc-modified-id="Bonus-Question-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Bonus Question</a></span></li></ul></div>

# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [2]:
# Import libraries
import numpy as np
import pandas as pd

In [4]:
# Importing the dataset from Ironhack's database
pokemon=pd.read_csv(r'/Users/nadimsaad/Desktop/IRONHACK/Week 3/Day 13/Pokemon.csv')
pokemon.shape
pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [5]:
pokemon["Total1"] =pokemon["HP"] + pokemon["Attack"]+ pokemon["Defense"]+ pokemon["Sp. Atk"] + pokemon["Sp. Def"]+ pokemon["Speed"]
print(pokemon["Total1"])

0      318
1      405
2      525
3      625
4      309
      ... 
795    600
796    700
797    600
798    680
799    600
Name: Total1, Length: 800, dtype: int64


Comment: Yeah, Total is just a sum of all those columns

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
x=[[1,'Grass'],[1,'Fire'],[1,'Water'],[1, 'Bug'],[1,'Normal'],[1,'Poison'],[1,'Electric'],[1,'Ground'],
   [1,'Fairy'],[1,'Fighting'],[1,'Psychic'],[1,'Rock'],[1,'Ghost'],[1,'Ice'],[1,'Dragon'],[1,'Dark'],[1,'Steel'],
   [1,'Flying'],[0,'NaN']]
y= OneHotEncoder().fit_transform(x).toarray()
print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0.

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [8]:
# pearson : standard correlation coefficient
y=pokemon.corr(method ='pearson')
# The correlation of a variable with itself is 1. For that reason the #1 pokemon type is value is 1

#     Total        HP    Attack   Defense   Sp. Atk  \
#           1.000000  0.119813  0.097614  0.102298  0.094786  0.088759   
Total       0.119813  1.000000  0.618748  0.736211  0.612787  0.747250   
HP          0.097614  0.618748  1.000000  0.422386  0.239622  0.362380   
Attack      0.102298  0.736211  0.422386  1.000000  0.438687  0.396362   
Defense     0.094786  0.612787  0.239622  0.438687  1.000000  0.223549   
Sp. Atk     0.088759  0.747250  0.362380  0.396362  0.223549  1.000000   
Sp. Def     0.085817  0.717609  0.378718  0.263990  0.510747  0.506121   
Speed       0.010733  0.575943  0.175952  0.381240  0.015227  0.473018   
Generation  0.982516  0.048384  0.058683  0.051451  0.042419  0.036437   
Legendary   0.153396  0.501758  0.273620  0.345408  0.246377  0.448907   
Total1      0.119813  1.000000  0.618748  0.736211  0.612787  0.747250   

             Sp. Def     Speed  Generation  Legendary    Total1  
#           0.085817  0.010733    0.982516   0.153396  0.119813  
Total       0.717609  0.575943    0.048384   0.501758  1.000000  
HP          0.378718  0.175952    0.058683   0.273620  0.618748  
Attack      0.263990  0.381240    0.051451   0.345408  0.736211  
Defense     0.510747  0.015227    0.042419   0.246377  0.612787  
Sp. Atk     0.506121  0.473018    0.036437   0.448907  0.747250  
Sp. Def     1.000000  0.259133    0.028486   0.363937  0.717609  
Speed       0.259133  1.000000   -0.023121   0.326715  0.575943  
Generation  0.028486 -0.023121    1.000000   0.079794  0.048384  
Legendary   0.363937  0.326715    0.079794   1.000000  0.501758  
Total1      0.717609  0.575943    0.048384   0.501758  1.000000

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here