# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
import numpy
print(numpy.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
# Method 1
a=np.arange(30).reshape(2,3,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [8]:
# Method 2
a2 = np.random.rand(2,4)

print(a2)

[[0.64219863 0.91615356 0.16695755 0.62945446]
 [0.81009686 0.18165128 0.61369339 0.56228308]]


In [9]:
# Method 3
a3 = np.random.rand(4,2,3)

print(a3)

[[[0.12271487 0.47035074 0.27376873]
  [0.53004614 0.24463314 0.59038857]]

 [[0.48158393 0.90064366 0.17469655]
  [0.48748119 0.90862087 0.06390476]]

 [[0.45906104 0.20762526 0.03609656]
  [0.31486469 0.20011815 0.5345844 ]]

 [[0.9258582  0.56623122 0.57203381]
  [0.51986191 0.01654364 0.6295039 ]]]


#### 4. Print *a*.


In [21]:
# Method 1:
print(a)
print(a2)
print(a3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[0.64219863 0.91615356 0.16695755 0.62945446]
 [0.81009686 0.18165128 0.61369339 0.56228308]]
[[[0.12271487 0.47035074 0.27376873]
  [0.53004614 0.24463314 0.59038857]]

 [[0.48158393 0.90064366 0.17469655]
  [0.48748119 0.90862087 0.06390476]]

 [[0.45906104 0.20762526 0.03609656]
  [0.31486469 0.20011815 0.5345844 ]]

 [[0.9258582  0.56623122 0.57203381]
  [0.51986191 0.01654364 0.6295039 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
#b = np.random.rand(5,2,3)
b= np.ones((5,2,3))

#### 6. Print *b*.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
print(a.shape)
print(b.shape) 
# No they have 2 different sizes

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
np.add(a,b) # since they are of 2 different shapes, the add operation couldn't be executed

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [35]:
c= numpy.reshape(b,(2,3,5))
print(c)
print(c.shape) 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [37]:
d=np.add(a,c)
d # both arrays a and c have the same shape now of 2x3x5

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]],

       [[16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [40]:
print(a) # Values in a are integers 
print(d) # Whereas in d they are floats

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
e=a*c
e

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]],

       [[15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
print(a)
print(e) # The values are equal but the value types are different (a is an integer and e a float)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [45]:
d_max=numpy.max(d)
print(d_max)
d_min=numpy.min(d)
print(d_min)
d_mean=numpy.mean(d)
print(d_mean)

30.0
1.0
15.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [53]:
f= np.empty(shape=[2, 3,5], dtype=int) 
# f= np.zeros(shape=[2, 3,5], dtype=int) to have a 3d array with zeros 
print(f)

[[[-5764607523034234880 -5764607523034234880                   21
                      0                    0]
  [ 7235419174270214779  3630808633868171810  4062922381397878327
    3558514654192940130  3690525309447398242]
  [ 3617571785217751345  8385534776637008930  8391088163801886841
    8440357178021340530  2478507435169572211]]

 [[ 8317419966675427898  7310224193103356257  2466321603649696627
    3775766027149326133  3545566800955990317]
  [ 3702911282872203619  7005684791393728312  7310575177827099191
    3256439188146502178  3832937336714113585]
  [ 3904110927849926714  3180203480039633718  7957695011148363298
    9016825677502102050                    0]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [63]:
f1 = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 50 if item == d_mean else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]
print(f1)

[[[0, 25, 25, 25, 25], [25, 25, 25, 25, 25], [25, 25, 25, 25, 25]], [[75, 75, 75, 75, 75], [75, 75, 75, 75, 75], [75, 75, 75, 75, 100]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [69]:
d=[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
print (d)
d_max=numpy.max(d)
print(d_max)
d_min=numpy.min(d)
print(d_min)
d_mean=numpy.mean(d)
print(d_mean)
f2 = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 50 if item == d_mean else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]
print(f2)

[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]
1.97066381
1.00656599
1.6175069086666667
[[[75, 75, 75, 25, 75], [75, 75, 25, 25, 25], [75, 25, 75, 75, 75]], [[25, 25, 25, 25, 100], [75, 75, 75, 75, 75], [25, 75, 0, 75, 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [70]:
f3 = [[["B" if d_min<item<d_mean else "D" if d_mean<item< d_max else "C" if item == d_mean else "A" if item == d_min else "E" for item in in_list] for in_list in out_list] for out_list in d]
print(f3)

[[['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'D', 'D']], [['B', 'B', 'B', 'B', 'E'], ['D', 'D', 'D', 'D', 'D'], ['B', 'D', 'A', 'D', 'D']]]
